apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-reverse
  labels:
    app: paymentservice-reverse
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: paymentservice-reverse
  template:
    metadata:
      labels:
        app: paymentservice-reverse
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image:  docker.io/mrvovanness/kubernetes-intro-web:demo-paymentservice-1
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
