apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image:  docker.io/mrvovanness/kubernetes-intro-web:demo-paymentservice-2
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
