apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  volumes:
    - name: app
      emptyDir: {}
  initContainers:
    - name: index-html-generator
      image: docker.io/library/busybox:1.33.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app
  containers:
    - name: web
      image: docker.io/mrvovanness/kubernetes-intro-web:2
      livenessProbe:
        tcpSocket: { port: 8000 }
      readinessProbe:
        httpGet:
          path: /index.html
          port: 80
      volumeMounts:
        - name: app
          mountPath: /app
